#import "GameSpriteData.h"

#define CAN_BUILD_ARROW_TOWER YES
#define CAN_BUILD_DEFENCE_TOWER YES
#define CAN_BUILD_TURRET_TOWER YES
#define CAN_BUILD_MAGIC_TOWER YES

#define CAN_UPDATE1_ARROW_TOWER YES
#define CAN_UPDATE1_DEFENCE_TOWER YES
#define CAN_UPDATE1_TURRET_TOWER YES
#define CAN_UPDATE1_MAGIC_TOWER YES

#define CAN_UPDATE2_ARROW_TOWER YES
#define CAN_UPDATE2_DEFENCE_TOWER YES
#define CAN_UPDATE2_TURRET_TOWER YES
#define CAN_UPDATE2_MAGIC_TOWER YES

#define CAN_UPDATE3_ARROW_TOWER NO
#define CAN_UPDATE3_DEFENCE_TOWER NO
#define CAN_UPDATE3_TURRET_TOWER NO
#define CAN_UPDATE3_MAGIC_TOWER NO

#define TDS_DT_FRIENDLY_NO 3