//===================塔数据配置======================
//箭塔的攻击时间 和 射程 卖的价格
#define TDS_ARROW_TOWER1_ATTACTRANGE 100
#define TDS_ARROW_TOWER1_ATTACTTIME 1.2
#define TDS_ARROW_TOWER1_BUYGOLD 70
#define TDS_ARROW_TOWER1_GETGOLD 35

#define TDS_ARROW_TOWER2_ATTACTRANGE 100
#define TDS_ARROW_TOWER2_ATTACTTIME 0.8
#define TDS_ARROW_TOWER2_BUYGOLD 120
#define TDS_ARROW_TOWER2_GETGOLD 95

#define TDS_ARROW_TOWER3_ATTACTRANGE 100
#define TDS_ARROW_TOWER3_ATTACTTIME 0.6
#define TDS_ARROW_TOWER3_BUYGOLD 120
#define TDS_ARROW_TOWER3_GETGOLD 165

//魔法塔的攻击时间 和 射程 卖的价格
#define TDS_MAGIC_TOWER1_ATTACTRANGE 100
#define TDS_MAGIC_TOWER1_ATTACTTIME 2
#define TDS_MAGIC_TOWER1_BUYGOLD 100
#define TDS_MAGIC_TOWER1_GETGOLD 50

#define TDS_MAGIC_TOWER2_ATTACTRANGE 100
#define TDS_MAGIC_TOWER2_ATTACTTIME 1.8
#define TDS_MAGIC_TOWER2_BUYGOLD 180
#define TDS_MAGIC_TOWER2_GETGOLD 140

#define TDS_MAGIC_TOWER3_ATTACTRANGE 100
#define TDS_MAGIC_TOWER3_ATTACTTIME 1.5
#define TDS_MAGIC_TOWER3_BUYGOLD 180
#define TDS_MAGIC_TOWER3_GETGOLD 220

//炮塔的攻击时间 和 射程 卖的价格
#define TDS_TURRET_TOWER1_ATTACTRANGE 100
#define TDS_TURRET_TOWER1_ATTACTTIME 2
#define TDS_TURRET_TOWER1_BUYGOLD 120
#define TDS_TURRET_TOWER1_GETGOLD 200

#define TDS_TURRET_TOWER2_ATTACTRANGE 100
#define TDS_TURRET_TOWER2_ATTACTTIME 1.8
#define TDS_TURRET_TOWER2_BUYGOLD 200
#define TDS_TURRET_TOWER2_GETGOLD 160

#define TDS_TURRET_TOWER3_ATTACTRANGE 100
#define TDS_TURRET_TOWER3_ATTACTTIME 1.7
#define TDS_TURRET_TOWER3_BUYGOLD 200
#define TDS_TURRET_TOWER3_GETGOLD 260

//防御的出兵时间 和 活动范围 卖的价格
#define TDS_DEFENCE_TOWER1_ATTACTRANGE 100
#define TDS_DEFENCE_TOWER1_ATTACTTIME 8
#define TDS_DEFENCE_TOWER1_BUYGOLD 70
#define TDS_DEFENCE_TOWER1_GETGOLD 35

#define TDS_DEFENCE_TOWER2_ATTACTRANGE 100
#define TDS_DEFENCE_TOWER2_ATTACTTIME 7
#define TDS_DEFENCE_TOWER2_BUYGOLD 100
#define TDS_DEFENCE_TOWER2_GETGOLD 85

#define TDS_DEFENCE_TOWER3_ATTACTRANGE 100
#define TDS_DEFENCE_TOWER3_ATTACTTIME 6
#define TDS_DEFENCE_TOWER3_BUYGOLD 100
#define TDS_DEFENCE_TOWER3_GETGOLD 135
//===================塔数据配置======================


//===================子弹数据配置======================
//箭塔子弹的攻击力 和 移动时间 射击模式
#define TDS_ARROW_BULLET1_ATTACT 5
#define TDS_ARROW_BULLET1_MOVETIME 0.8
#define TDS_ARROW_BULLET1_ATTACTMODE AT_NORMAL

#define TDS_ARROW_BULLET2_ATTACT 10
#define TDS_ARROW_BULLET2_MOVETIME 0.8
#define TDS_ARROW_BULLET2_ATTACTMODE AT_NORMAL

#define TDS_ARROW_BULLET3_ATTACT 20
#define TDS_ARROW_BULLET3_MOVETIME 0.8
#define TDS_ARROW_BULLET3_ATTACTMODE AT_NORMAL

//魔法塔的攻击时间 和 射程 卖的价格
#define TDS_MAGIC_BULLET1_ATTACT 20
#define TDS_MAGIC_BULLET1_MOVETIME 0.9
#define TDS_MAGIC_BULLET1_ATTACTMODE AT_NORMAL

#define TDS_MAGIC_BULLET2_ATTACT 35
#define TDS_MAGIC_BULLET2_MOVETIME 0.9
#define TDS_MAGIC_BULLET2_ATTACTMODE AT_NORMAL

#define TDS_MAGIC_BULLET3_ATTACT 60
#define TDS_MAGIC_BULLET3_MOVETIME 0.9
#define TDS_MAGIC_BULLET3_ATTACTMODE AT_NORMAL

//炮塔的攻击时间 和 射程 卖的价格
#define TDS_TURRET_BULLET1_ATTACT 15
#define TDS_TURRET_BULLET1_MOVETIME 1
#define TDS_TURRET_BULLET1_ATTACTMODE AT_NORMAL
#define TDS_TURRET_BULLET1_RANGE 100

#define TDS_TURRET_BULLET2_ATTACT 25
#define TDS_TURRET_BULLET2_MOVETIME 1
#define TDS_TURRET_BULLET2_ATTACTMODE AT_NORMAL
#define TDS_TURRET_BULLET2_RANGE 100

#define TDS_TURRET_BULLET3_ATTACT 40
#define TDS_TURRET_BULLET3_MOVETIME 1
#define TDS_TURRET_BULLET3_ATTACTMODE AT_NORMAL
#define TDS_TURRET_BULLET3_RANGE 100

//魔法子弹的数值，火焰，雷电，石头

#define MC_FIRE_BULLET_ATTACT 15
#define MC_FIRE_BULLET_MOVETIME 1
#define MC_FIRE_BULLET_ATTACTMODE AT_NORMAL
#define MC_FIRE_BULLET_RANGE 100

#define MC_THUNDER_BULLET_ATTACT 25
#define MC_THUNDER_BULLET_MOVETIME 1
#define MC_THUNDER_BULLET_ATTACTMODE AT_NORMAL

#define MC_STONE_BULLET_ATTACT 40
#define MC_STONE_BULLET_MOVETIME 1
#define MC_STONE_BULLET_ATTACTMODE AT_NORMAL
#define MC_STONE_BULLET_FAINTTIME 100
//===================子弹数据配置======================

//===================敌军数据配置======================

//===================步兵数据配置======================
#define TDS_FT1_SCALE 0.85
#define TDS_FT1_MAXHP 30
#define TDS_FT1_CURRENTHP TDS_FT1_MAXHP
#define TDS_FT1_MOVESPEED 15
#define TDS_FT1_ATTACTTIME 1.8
#define TDS_FT1_ATTACTRANGE 0
#define TDS_FT1_ATTACT 5
#define TDS_FT1_ATTACTMODE AT_NORMAL
#define TDS_FT1_DEFENCE 0
#define TDS_FT1_DEFENCEMODE DT_NO
#define TDS_FT1_GETGOLD 5

#define TDS_FT2_SCALE 0.85
#define TDS_FT2_MAXHP 40
#define TDS_FT2_CURRENTHP TDS_FT2_MAXHP
#define TDS_FT2_MOVESPEED 20
#define TDS_FT2_ATTACTTIME 1.8
#define TDS_FT2_ATTACTRANGE 0
#define TDS_FT2_ATTACT 8
#define TDS_FT2_ATTACTMODE AT_NORMAL
#define TDS_FT2_DEFENCE 0
#define TDS_FT2_DEFENCEMODE DT_NO
#define TDS_FT2_GETGOLD 8

#define TDS_FT3_SCALE 0.85
#define TDS_FT3_MAXHP 40
#define TDS_FT3_CURRENTHP TDS_FT3_MAXHP
#define TDS_FT3_MOVESPEED 20
#define TDS_FT3_ATTACTTIME 1.8
#define TDS_FT3_ATTACTRANGE 0
#define TDS_FT3_ATTACT 8
#define TDS_FT3_ATTACTMODE AT_NORMAL
#define TDS_FT3_DEFENCE 0
#define TDS_FT3_DEFENCEMODE DT_NO
#define TDS_FT3_GETGOLD 8

#define TDS_FT4_SCALE 0.95
#define TDS_FT4_MAXHP 60
#define TDS_FT4_CURRENTHP TDS_FT4_MAXHP
#define TDS_FT4_MOVESPEED 25
#define TDS_FT4_ATTACTTIME 1.8
#define TDS_FT4_ATTACTRANGE 0
#define TDS_FT4_ATTACT 15
#define TDS_FT4_ATTACTMODE AT_NORMAL
#define TDS_FT4_DEFENCE 0
#define TDS_FT4_DEFENCEMODE DT_NO
#define TDS_FT4_GETGOLD 10

#define TDS_FT5_SCALE 1
#define TDS_FT5_MAXHP 60
#define TDS_FT5_CURRENTHP TDS_FT5_MAXHP
#define TDS_FT5_MOVESPEED 25
#define TDS_FT5_ATTACTTIME 1.8
#define TDS_FT5_ATTACTRANGE 0
#define TDS_FT5_ATTACT 15
#define TDS_FT5_ATTACTMODE AT_NORMAL
#define TDS_FT5_DEFENCE 0
#define TDS_FT5_DEFENCEMODE DT_NO
#define TDS_FT5_GETGOLD 12

#define TDS_FT6_SCALE 0.85
#define TDS_FT6_MAXHP 60
#define TDS_FT6_CURRENTHP TDS_FT6_MAXHP
#define TDS_FT6_MOVESPEED 35
#define TDS_FT6_ATTACTTIME 1.8
#define TDS_FT6_ATTACTRANGE 0
#define TDS_FT6_ATTACT 15
#define TDS_FT6_ATTACTMODE AT_NORMAL
#define TDS_FT6_DEFENCE 0
#define TDS_FT6_DEFENCEMODE DT_NO
#define TDS_FT6_GETGOLD 12

#define TDS_FT7_SCALE 0.75
#define TDS_FT7_MAXHP 100
#define TDS_FT7_CURRENTHP TDS_FT7_MAXHP
#define TDS_FT7_MOVESPEED 25
#define TDS_FT7_ATTACTTIME 1.8
#define TDS_FT7_ATTACTRANGE 0
#define TDS_FT7_ATTACT 15
#define TDS_FT7_ATTACTMODE AT_NORMAL
#define TDS_FT7_DEFENCE 0
#define TDS_FT7_DEFENCEMODE DT_NO
#define TDS_FT7_GETGOLD 15

#define TDS_FT8_SCALE 0.8
#define TDS_FT8_MAXHP 100
#define TDS_FT8_CURRENTHP TDS_FT8_MAXHP
#define TDS_FT8_MOVESPEED 35
#define TDS_FT8_ATTACTTIME 1.8
#define TDS_FT8_ATTACTRANGE 0
#define TDS_FT8_ATTACT 15
#define TDS_FT8_ATTACTMODE AT_NORMAL
#define TDS_FT8_DEFENCE 0
#define TDS_FT8_DEFENCEMODE DT_NO
#define TDS_FT8_GETGOLD 15

#define TDS_FT9_SCALE 1
#define TDS_FT9_MAXHP 150
#define TDS_FT9_CURRENTHP TDS_FT9_MAXHP
#define TDS_FT9_MOVESPEED 22
#define TDS_FT9_ATTACTTIME 1.8
#define TDS_FT9_ATTACTRANGE 0
#define TDS_FT9_ATTACT 20
#define TDS_FT9_ATTACTMODE AT_NORMAL
#define TDS_FT9_DEFENCE 0
#define TDS_FT9_DEFENCEMODE DT_NO
#define TDS_FT9_GETGOLD 20

#define TDS_FT10_SCALE 1
#define TDS_FT10_MAXHP 150
#define TDS_FT10_CURRENTHP TDS_FT10_MAXHP
#define TDS_FT10_MOVESPEED 20
#define TDS_FT10_ATTACTTIME 1.8
#define TDS_FT10_ATTACTRANGE 0
#define TDS_FT10_ATTACT 20
#define TDS_FT10_ATTACTMODE AT_NORMAL
#define TDS_FT10_DEFENCE 0
#define TDS_FT10_DEFENCEMODE DT_NO
#define TDS_FT10_GETGOLD 20

#define TDS_FT11_SCALE 0.95
#define TDS_FT11_MAXHP 220
#define TDS_FT11_CURRENTHP TDS_FT11_MAXHP
#define TDS_FT11_MOVESPEED 20
#define TDS_FT11_ATTACTTIME 1.8
#define TDS_FT11_ATTACTRANGE 0
#define TDS_FT11_ATTACT 30
#define TDS_FT11_ATTACTMODE AT_NORMAL
#define TDS_FT11_DEFENCE 0
#define TDS_FT11_DEFENCEMODE DT_NO
#define TDS_FT11_GETGOLD 30

#define TDS_FT12_SCALE 0.95
#define TDS_FT12_MAXHP 230
#define TDS_FT12_CURRENTHP TDS_FT12_MAXHP
#define TDS_FT12_MOVESPEED 20
#define TDS_FT12_ATTACTTIME 1.8
#define TDS_FT12_ATTACTRANGE 0
#define TDS_FT12_ATTACT 30
#define TDS_FT12_ATTACTMODE AT_NORMAL
#define TDS_FT12_DEFENCE 0
#define TDS_FT12_DEFENCEMODE DT_NO
#define TDS_FT12_GETGOLD 30

#define TDS_FT13_SCALE 0.95
#define TDS_FT13_MAXHP 220
#define TDS_FT13_CURRENTHP TDS_FT13_MAXHP
#define TDS_FT13_MOVESPEED 20
#define TDS_FT13_ATTACTTIME 1.8
#define TDS_FT13_ATTACTRANGE 0
#define TDS_FT13_ATTACT 30
#define TDS_FT13_ATTACTMODE AT_NORMAL
#define TDS_FT13_DEFENCE 0
#define TDS_FT13_DEFENCEMODE DT_NO
#define TDS_FT13_GETGOLD 30

#define TDS_FT14_SCALE 0.9
#define TDS_FT14_MAXHP 250
#define TDS_FT14_CURRENTHP TDS_FT14_MAXHP
#define TDS_FT14_MOVESPEED 20
#define TDS_FT14_ATTACTTIME 1.8
#define TDS_FT14_ATTACTRANGE 0
#define TDS_FT14_ATTACT 30
#define TDS_FT14_ATTACTMODE AT_NORMAL
#define TDS_FT14_DEFENCE 0
#define TDS_FT14_DEFENCEMODE DT_NO
#define TDS_FT14_GETGOLD 35

#define TDS_FT15_SCALE 0.85
#define TDS_FT15_MAXHP 350
#define TDS_FT15_CURRENTHP TDS_FT15_MAXHP
#define TDS_FT15_MOVESPEED 20
#define TDS_FT15_ATTACTTIME 1.8
#define TDS_FT15_ATTACTRANGE 0
#define TDS_FT15_ATTACT 50
#define TDS_FT15_ATTACTMODE AT_NORMAL
#define TDS_FT15_DEFENCE 0
#define TDS_FT15_DEFENCEMODE DT_NO
#define TDS_FT15_GETGOLD 40

#define TDS_FT16_SCALE 0.85
#define TDS_FT16_MAXHP 350
#define TDS_FT16_CURRENTHP TDS_FT16_MAXHP
#define TDS_FT16_MOVESPEED 20
#define TDS_FT16_ATTACTTIME 1.8
#define TDS_FT16_ATTACTRANGE 0
#define TDS_FT16_ATTACT 50
#define TDS_FT16_ATTACTMODE AT_NORMAL
#define TDS_FT16_DEFENCE 0
#define TDS_FT16_DEFENCEMODE DT_NO
#define TDS_FT16_GETGOLD 40
//===================步兵数据配置======================

//===================飞行兵数据配置======================
#define TDS_FL1_SCALE 0.65
#define TDS_FL1_MAXHP 40
#define TDS_FL1_CURRENTHP TDS_FL1_MAXHP
#define TDS_FL1_MOVESPEED 25
#define TDS_FL1_ATTACTTIME 1.2
#define TDS_FL1_ATTACTRANGE 0
#define TDS_FL1_ATTACT 8
#define TDS_FL1_ATTACTMODE AT_NORMAL
#define TDS_FL1_DEFENCE 0
#define TDS_FL1_DEFENCEMODE DT_NO

#define TDS_FL2_SCALE 0.65
#define TDS_FL2_MAXHP 60
#define TDS_FL2_CURRENTHP TDS_FL2_MAXHP
#define TDS_FL2_MOVESPEED 25
#define TDS_FL2_ATTACTTIME 1.2
#define TDS_FL2_ATTACTRANGE 0
#define TDS_FL2_ATTACT 8
#define TDS_FL2_ATTACTMODE AT_NORMAL
#define TDS_FL2_DEFENCE 0
#define TDS_FL2_DEFENCEMODE DT_NO

#define TDS_FL3_SCALE 0.65
#define TDS_FL3_MAXHP 60
#define TDS_FL3_CURRENTHP TDS_FL3_MAXHP
#define TDS_FL3_MOVESPEED 30
#define TDS_FL3_ATTACTTIME 1.2
#define TDS_FL3_ATTACTRANGE 0
#define TDS_FL3_ATTACT 8
#define TDS_FL3_ATTACTMODE AT_NORMAL
#define TDS_FL3_DEFENCE 0
#define TDS_FL3_DEFENCEMODE DT_NO
//===================飞行兵数据配置======================

//===================魔法兵数据配置======================
#define TDS_MC1_SCALE 0.65
#define TDS_MC1_MAXHP 100
#define TDS_MC1_CURRENTHP TDS_MC1_MAXHP
#define TDS_MC1_MOVESPEED 20
#define TDS_MC1_ATTACTTIME 1.2
#define TDS_MC1_ATTACTRANGE 0
#define TDS_MC1_ATTACT 8
#define TDS_MC1_ATTACTMODE AT_NORMAL
#define TDS_MC1_DEFENCE 0
#define TDS_MC1_DEFENCEMODE DT_NO

#define TDS_MC2_SCALE 0.65
#define TDS_MC2_MAXHP 100
#define TDS_MC2_CURRENTHP TDS_MC2_MAXHP
#define TDS_MC2_MOVESPEED 20
#define TDS_MC2_ATTACTTIME 1.2
#define TDS_MC2_ATTACTRANGE 0
#define TDS_MC2_ATTACT 8
#define TDS_MC2_ATTACTMODE AT_NORMAL
#define TDS_MC2_DEFENCE 0
#define TDS_MC2_DEFENCEMODE DT_NO
//===================魔法兵数据配置======================

//===================远程兵数据配置======================
#define TDS_ST1_SCALE 0.65
#define TDS_ST1_MAXHP 100
#define TDS_ST1_CURRENTHP TDS_ST1_MAXHP
#define TDS_ST1_MOVESPEED 20
#define TDS_ST1_ATTACTTIME 1.2
#define TDS_ST1_ATTACTRANGE 0
#define TDS_ST1_ATTACT 8
#define TDS_ST1_ATTACTMODE AT_NORMAL
#define TDS_ST1_DEFENCE 0
#define TDS_ST1_DEFENCEMODE DT_NO
//===================远程兵数据配置======================

//===================老怪数据配置======================
#define TDS_BS1_SCALE 0.65
#define TDS_BS1_MAXHP 100
#define TDS_BS1_CURRENTHP TDS_BS1_MAXHP
#define TDS_BS1_MOVESPEED 20
#define TDS_BS1_ATTACTTIME 1.2
#define TDS_BS1_ATTACTRANGE 0
#define TDS_BS1_ATTACT 8
#define TDS_BS1_ATTACTMODE AT_NORMAL
#define TDS_BS1_DEFENCE 0
#define TDS_BS1_DEFENCEMODE DT_NO

#define TDS_BS2_SCALE 0.65
#define TDS_BS2_MAXHP 100
#define TDS_BS2_CURRENTHP TDS_BS2_MAXHP
#define TDS_BS2_MOVESPEED 20
#define TDS_BS2_ATTACTTIME 1.2
#define TDS_BS2_ATTACTRANGE 0
#define TDS_BS2_ATTACT 8
#define TDS_BS2_ATTACTMODE AT_NORMAL
#define TDS_BS2_DEFENCE 0
#define TDS_BS2_DEFENCEMODE DT_NO
//===================老怪数据配置======================

//===================敌军数据配置======================

//===================友军数据配置======================

#define TDS_TFL1_SCALE 0.65
#define TDS_TFL1_MAXHP 100
#define TDS_TFL1_CURRENTHP TDS_BS2_MAXHP
#define TDS_TFL1_MOVESPEED 20
#define TDS_TFL1_ATTACTTIME 1.2
#define TDS_TFL1_ATTACTRANGE 0
#define TDS_TFL1_SEARCHRANGE 0
#define TDS_TFL1_ATTACT 8
#define TDS_TFL1_ATTACTMODE AT_NORMAL
#define TDS_TFL1_DEFENCE 0
#define TDS_TFL1_DEFENCEMODE DT_NO

#define TDS_TFL2_SCALE 0.65
#define TDS_TFL2_MAXHP 100
#define TDS_TFL2_CURRENTHP TDS_BS2_MAXHP
#define TDS_TFL2_MOVESPEED 20
#define TDS_TFL2_ATTACTTIME 1.2
#define TDS_TFL2_ATTACTRANGE 0
#define TDS_TFL2_SEARCHRANGE 0
#define TDS_TFL2_ATTACT 8
#define TDS_TFL2_ATTACTMODE AT_NORMAL
#define TDS_TFL2_DEFENCE 0
#define TDS_TFL2_DEFENCEMODE DT_NO

#define TDS_TFL3_SCALE 0.65
#define TDS_TFL3_MAXHP 100
#define TDS_TFL3_CURRENTHP TDS_BS2_MAXHP
#define TDS_TFL3_MOVESPEED 20
#define TDS_TFL3_ATTACTTIME 1.2
#define TDS_TFL3_ATTACTRANGE 0
#define TDS_TFL3_SEARCHRANGE 0
#define TDS_TFL3_ATTACT 8
#define TDS_TFL3_ATTACTMODE AT_NORMAL
#define TDS_TFL3_DEFENCE 0
#define TDS_TFL3_DEFENCEMODE DT_NO


#define TDS_MFL1_SCALE 0.65
#define TDS_MFL1_MAXHP 100
#define TDS_MFL1_CURRENTHP TDS_BS2_MAXHP
#define TDS_MFL1_MOVESPEED 20
#define TDS_MFL1_ATTACTTIME 1.2
#define TDS_MFL1_ATTACTRANGE 0
#define TDS_MFL1_SEARCHRANGE 0
#define TDS_MFL1_ATTACT 8
#define TDS_MFL1_ATTACTMODE AT_NORMAL
#define TDS_MFL1_DEFENCE 0
#define TDS_MFL1_DEFENCEMODE DT_NO
#define TDS_MFL1_DEADTIME 10

#define TDS_MFL2_SCALE 0.65
#define TDS_MFL2_MAXHP 100
#define TDS_MFL2_CURRENTHP TDS_BS2_MAXHP
#define TDS_MFL2_MOVESPEED 20
#define TDS_MFL2_ATTACTTIME 1.2
#define TDS_MFL2_ATTACTRANGE 0
#define TDS_MFL2_SEARCHRANGE 0
#define TDS_MFL2_ATTACT 8
#define TDS_MFL2_ATTACTMODE AT_NORMAL
#define TDS_MFL2_DEFENCE 0
#define TDS_MFL2_DEFENCEMODE DT_NO
#define TDS_MFL2_DEADTIME 10

#define TDS_FFL1_SCALE 0.65
#define TDS_FFL1_MAXHP 100
#define TDS_FFL1_CURRENTHP TDS_BS2_MAXHP
#define TDS_FFL1_MOVESPEED 20
#define TDS_FFL1_ATTACTTIME 1.2
#define TDS_FFL1_ATTACTRANGE 0
#define TDS_FFL1_SEARCHRANGE 0
#define TDS_FFL1_ATTACT 8
#define TDS_FFL1_ATTACTMODE AT_NORMAL
#define TDS_FFL1_DEFENCE 0
#define TDS_FFL1_DEFENCEMODE DT_NO

#define TDS_FFL2_SCALE 0.65
#define TDS_FFL2_MAXHP 100
#define TDS_FFL2_CURRENTHP TDS_BS2_MAXHP
#define TDS_FFL2_MOVESPEED 20
#define TDS_FFL2_ATTACTTIME 1.2
#define TDS_FFL2_ATTACTRANGE 0
#define TDS_FFL2_SEARCHRANGE 0
#define TDS_FFL2_ATTACT 8
#define TDS_FFL2_ATTACTMODE AT_NORMAL
#define TDS_FFL2_DEFENCE 0
#define TDS_FFL2_DEFENCEMODE DT_NO
//===================友军数据配置======================
